git clone git://git.postgresql.org/git/postgresql.git
git clone git://xmlstar.git.sourceforge.net/gitroot/xmlstar/xmlstar
git clone https://git.cms.waikato.ac.nz/weka/weka.git
git clone https://git.code.sf.net/p/scribus/code
git clone https://git.eclipse.org/r/tracecompass/org.eclipse.tracecompass.git
git clone https://git.savannah.gnu.org/git/pspp.git
git clone https://gitbox.apache.org/repos/asf/hadoop.git
git clone https://github.com/allegro/tipboard.git
git clone https://github.com/apache/jmeter.git
git clone https://github.com/apache/kylin
git clone https://github.com/apache/ofbiz-framework.git
git clone https://github.com/apache/pdfbox.git
git clone https://github.com/apache/pinot.git
git clone https://github.com/apache/superset.git
git clone https://github.com/apollographql/apollo-kotlin-tutorial
git clone https://github.com/apollographql/apollo-kotlin.git
git clone https://github.com/bittorrent/bittorrent.org.git
git clone https://github.com/bvschaik/julius.git
git clone https://github.com/containers/podman-desktop.git
git clone https://github.com/dashbuilder/dashbuilder.git
git clone https://github.com/dbeaver/dbeaver.git
git clone https://github.com/eclipse-birt/birt.git
git clone https://github.com/eclipse-platform/eclipse.platform.releng.aggregator.git
git clone https://github.com/eclipse-tycho/tycho.git
git clone https://github.com/ethereum-lists/chains.git
git clone https://github.com/ethereum/go-ethereum.git
git clone https://github.com/frappe/frappe_docker
git clone https://github.com/getredash/redash.git
git clone https://github.com/iamcryptoki/snowden-archive.git
git clone https://github.com/id-Software/Quake-III-Arena.git
git clone https://github.com/ioquake/ioq3.git
git clone https://github.com/ipfs-shipyard/java-ipfs-http-client.git
git clone https://github.com/ipfs/go-ipfs.git
git clone https://github.com/JabRef/jabref.git
git clone https://github.com/Johnnei/JavaTorrent.git
git clone https://github.com/jenkinsci/jenkins.git
git clone https://github.com/kiegroup/kie-tools.git
git clone https://github.com/Kong/insomnia.git
git clone https://github.com/kovidgoyal/calibre.git
git clone https://github.com/LibrePDF/OpenPDF.git
git clone https://github.com/LucidDB/luciddb.git
git clone https://github.com/LuminanceHDR/LuminanceHDR.git
git clone https://github.com/maks/MGit.git
git clone https://github.com/nusharama/ETL-Project.git
git clone https://github.com/olap4j/olap4j-xmlaserver.git
git clone https://github.com/olap4j/olap4j.git
git clone https://github.com/OpenRefine/OpenRefine.git
git clone https://github.com/opentomb/OpenTomb.git
git clone https://github.com/OpenTTD/OpenTTD.git
git clone https://github.com/plouc/mozaik.git
git clone https://github.com/rochus-keller/LeanQt.git
git clone https://github.com/SchemaStore/schemastore.git
git clone https://github.com/SmartBear/soapui.git
git clone https://github.com/Smashing/smashing.git
git clone https://github.com/soumyajitsamanta/libtorrent4j.git
git clone https://github.com/soumyajitsamanta/public-resources.git
git clone https://github.com/soumyajitsamanta/shastras.git
git clone https://github.com/soumyajitsamanta/soumyajitsamanta.github.io.git
git clone https://github.com/soumyajitsamanta/Subreddit-Display-UI.git
git clone https://github.com/sushiswap/sushiswap-interface.git
git clone https://github.com/sushiswap/sushiswap.git
git clone https://github.com/Talend/tdi-studio-se.git
git clone https://github.com/the-markup/xandr-audience-segments.git
git clone https://github.com/Uniswap/v2-core.git
git clone https://github.com/Uniswap/v2-periphery.git
git clone https://github.com/Uniswap/v3-core.git
git clone https://github.com/Uniswap/v3-periphery.git
git clone https://github.com/xwlcn/Dodder.git
git clone https://gitlab.com/baserow/baserow.git
git clone https://gitlab.gnome.org/GNOME/gimp.git
git clone https://gitlab.winehq.org/wine/wine.git
git clone https://github.com/pentaho/maven-parent-poms.git ./pentaho-collections/maven-parent-poms
git clone https://github.com/pentaho/metastore.git         ./pentaho-collections/metastore
git clone https://github.com/pentaho/mondrian.git          ./pentaho-collections/mondrian
git clone https://github.com/pentaho/pentaho-kettle.git    ./pentaho-collections/pentaho-kettle
git clone https://github.com/knime/knime-sdk-setup.git
git clone https://github.com/knime/knime-workbench.git
git clone https://github.com/apache/zeppelin.git
git clone https://github.com/apache/hop.git
git clone https://github.com/sonatype/nexus-public.git
git clone https://github.com/openrewrite/rewrite.git
git clone https://github.com/distribution/distribution.git
git clone git://git.netsurf-browser.org/netsurf.git
git clone https://github.com/eclipse-jgit/jgit.git
git clone https://github.com/ImageMagick/ImageMagick.git
git clone https://github.com/strukturag/libheif
git clone https://github.com/strukturag/libde265
git clone https://github.com/joncampbell123/dosbox-x.git
git clone https://github.com/symbl-cc/symbl-data.git
git clone https://github.com/metabase/metabase.git
git clone https://github.com/kiegroup/jbpm.git
git clone https://github.com/kiegroup/drools.git
git clone https://github.com/kiegroup/jbpm-wb.git
git clone https://github.com/kiegroup/kie-wb-distributions.git
git clone https://github.com/sanbornm/xsdtohtml.git
git clone https://github.com/sindresorhus/awesome.git
git clone https://github.com/remkop/picocli.git
git clone https://github.com/keycloak/keycloak.git
git clone https://github.com/transmission/transmission.git
git clone https://github.com/FascinatedBox/bonk.git
git clone https://github.com/AmrDeveloper/GQL.git
git clone https://github.com/PaddlePaddle/VisualDL.git
git clone https://github.com/zetane/viewer.git
git clone https://github.com/lutzroeder/netron.git
git clone https://github.com/oracle/fastr.git
git clone https://github.com/apache/echarts.git
git clone https://github.com/tensorflow/tensorboard.git
git clone https://github.com/onnx/onnx.git
git clone https://github.com/microsoft/onnxruntime.git
git clone https://github.com/apache/skywalking.git
